version: "3"
services:
    api:
        build: .
        restart: always
        env_file: .env
        depends_on:
            - mysql
    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-passwd
        command: --default-authentication-plugin=mysql_native_password
